### PR TITLE
Update

### PR DESCRIPTION
**Pull request by tiviyaa**

### CODE REVIEW

**Comment by B190102B** [comment]
I saw u still store the image on local devices,
just like what I mentioned in the issue, since u upload images to Firestore, than r no need to save in local anymore

**Comment by tiviyaa** [comment]
> I saw u still store the image on local devices, just like what I mentioned in the issue, since u upload images to Firestore, than r no need to save in local anymore

**Comment by tiviyaa** [comment]
> > I saw u still store the image on local devices, just like what I mentioned in the issue, since u upload images to Firestore, than r no need to save in local anymore

**Comment by B190102B** [comment]
Very Good, you need to add issues to this PR.
Then, try to resolve the conflicts and merge them into master.

**Pull request merged**
